name: CD

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Déployer dans le dossier permanent
        run: |
          cd /home/albert/log430-labo3
          git pull origin main

          cat > .env << EOF
          MYSQL_ROOT_PASSWORD=root
          MYSQL_DATABASE=labo03_db
          MYSQL_USER=labo03
          MYSQL_PASSWORD=labo03

          DB_HOST=mysql
          DB_PORT=3306
          DB_NAME=labo03_db
          DB_USER=labo03
          DB_PASS=labo03
          DB_PASSWORD=labo03

          REDIS_HOST=redis
          REDIS_PORT=6379
          REDIS_DB=0
          EOF

          docker network inspect labo03-network >/dev/null 2>&1 || docker network create labo03-network
          docker compose down
          docker compose up -d --build
          docker compose ps